# GIK2NX - Lab 2

## Task 1

In [1]:
# Find the value of x
def calculate_x(a, b):
    if not (0 <= a <= 9 and 0 <= b <= 9):
        raise ValueError("a and b must be positive integers less than 10.")
    x = a + b
    return x


a = 5
b = 7
x = calculate_x(a, b)

print(f"{x} = {a} + {b}")


12 = 5 + 7


## Task 2

In [2]:
# Find the value of y
import numpy as np

def calculate_y(a, b):
    a = np.array(a, dtype=np.float64)
    b = np.array(b, dtype=np.float64)

    # Check if elements in a and b are within the specified range
    if np.any(a >= 100) or np.any(b >= 100) or np.any(a <= 0) or np.any(b <= 0):
        raise ValueError("Elements in a and b must be positive integers less than 100.")

    # Ensure the length of a and b does not exceed n=50 and m=40 respectively
    if len(a) > 50 or len(b) > 40:
        raise ValueError("Length of array a must not exceed 50 and length of array b must not exceed 40.")

    # Calculate the first summation
    n = len(a)
    a_padded = np.pad(a, (0, max(0, n - len(a))), constant_values=0)[:n]
    b_padded = np.pad(b, (0, max(0, n - len(b))), constant_values=0)[:n]
    first_sum = np.sum((a_padded**4 + b_padded**2)**3)

    # Calculate the second summation
    m = len(b)
    a_padded_m = np.pad(a, (0, max(0, m - len(a))), constant_values=0)[:m]
    b_padded_m = np.pad(b, (0, max(0, m - len(b))), constant_values=0)[:m]
    second_sum = np.sum((a_padded_m**2 - b_padded_m)**2)

    # Return the sum of the two summations
    return first_sum + second_sum


# Generate random arrays for a and b with integers between 1 and 100
np.random.seed(1234)  # Set a seed for reproducibility
a = np.random.randint(1, 100, 50)
b = np.random.randint(1, 100, 40)

# Print a and b
# print(a)
# print(b)

# Calculate the result of the expression
result_with_large_numbers = calculate_y(a, b)
print("Result:", result_with_large_numbers)


Result: 2.6666864004685527e+24


## Task 3

In [3]:
# Find the value of Z
import numpy as np

matrix_rows = 2500
matrix_cols = 2500
integer_max = 10000

def calculate_z(A1, A2, B1, B2):
    if A1.shape != (matrix_rows, matrix_cols) or A2.shape != (matrix_rows, matrix_cols) or B1.shape != (matrix_rows, matrix_cols) or B2.shape != (matrix_rows, matrix_cols):
        raise ValueError("Dimensions of A1, A2, B1, and B2 must be ${matrix_rows}x${matrix_cols}.")
    if np.any(A1 >= integer_max) or np.any(A2 >= integer_max) or np.any(B1 >= integer_max) or np.any(B2 >= integer_max) or np.any(A1 <= 0) or np.any(A2 <= 0) or np.any(B1 <= 0) or np.any(B2 <= 0):
        raise ValueError("Elements in A1, A2, B1, and B2 must be positive integers less than ${integer_max}.")

    # Calculate Z1, Z2, and Z
    Z1 = A1 * B1
    Z2 = A2 * B2
    Z = Z1 + Z2
    return Z


np.random.seed(1234)  # Set a seed for reproducibility
A1 = np.random.randint(1, integer_max, (matrix_rows, matrix_cols))
A2 = np.random.randint(1, integer_max, (matrix_rows, matrix_cols))
B1 = np.random.randint(1, integer_max, (matrix_rows, matrix_cols))
B2 = np.random.randint(1, integer_max, (matrix_rows, matrix_cols))

# Calculate Z
Z = calculate_z(A1, A2, B1, B2)

# Print Z
print(Z)


[[ 50390832  34967487 147398176 ...  30872438  28894746  40903892]
 [ 29154856  33472479  28381554 ...  54247154  18359643  89394440]
 [ 28317410  57919732  16417455 ... 109737698  74533280 104567332]
 ...
 [ 47494397  90449154   6301066 ...  45331291  36648112  12765396]
 [ 71952797  45472765 127736972 ...  32591268  25967734  17803088]
 [ 57968281  81975540  95742316 ...  66894480 102142379  87345432]]
